### ISSUE TITLE
Usage of Guzzle function without Guzzle as a dependency

### ISSUE THREAD

**Issue by jdreesen** [DivineOmega/is_offensive#5]
Guzzle is not a Composer dependency of this library. 
https://github.com/DivineOmega/is_offensive/blob/c01fd1d808984d9af60eefd53615c43e9ced7e61/composer.json#L24-L26

Thus, the following line won't work:
https://github.com/DivineOmega/is_offensive/blob/c01fd1d808984d9af60eefd53615c43e9ced7e61/src/OffensiveChecker.php#L6

**Comment by Jord-JD** [comment]
@jdreesen Good catch. Thanks. This is supposed to be just the global PHP `json_decode` function. I think my IDE might have added this `use` line.

**Comment by Jord-JD** [comment]
Fixed in v1.3.1. Thanks for the report.
